apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx

# kubectl create -f <filename>

# kubectl get pods

# kubectl describe pod <pod-name>